### ISSUE TITLE
[Link to pages] are not working correctly

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/dmse-documentation#20]
A click on one of the section links (different pages from index page) doesn't open the page on the corresponding section.

e.g. input this link in the browser https://openmobilealliance.github.io/dmse-documentation/enablers#v10-functionality,
the page will open correctly in the section but the link available in the browser will miss the name of the file, in this example `enablers`.

**Comment by rubystream** [comment]
The links to pages, like [https://guidelines.openmobilealliance.org/enablers#lwm2m-event-log](https://guidelines.openmobilealliance.org/enablers#lwm2m-event-log), are working as there is no longer need for `base` router instruction as the web site is under [https://guidelines.openmobilealliance.org/](https://guidelines.openmobilealliance.org/)  DNS.

**Comment by jpradocueva** [comment]
It is working correctly, but I still don't understand why now is working and before it diddn't.

**Comment by rubystream** [comment]
In order to serve the project page as GitHub pages of **openmobilealliance** account the router base was added  that actualluy add the `base` element to the web page like in the following example:

```html
<head>
    <base href="https://openmobilealliance.github.io/dmse-documentation/" />
</head>
```

Base href affects anything on the page that isn't using a complete Url for href or src. Anything with an absolute or relative path in href or src will be affected by this change. This includes: a, img, style, script, etc.
For this reason the anchor links were nor resolved as we expected and produced the wrong behaviour.

Once we introduced the custom DNS we removed the base element and anchor links now works as expected.

It's nothing to do with our code but with flow in browser interpretation of anchor links.
