### ISSUE TITLE
Enhance Search with Algolia

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/dmse-documentation#7]

**Comment by jpradocueva** [comment]
The search function doesn't seem to be working correctly. 
It seems that only search on the index page.

**Comment by rubystream** [comment]
In oder to enable the search capabilities the Algolia API keys need to be provided as presented on https://content.nuxtjs.org/themes/docs/#properties page under `algolia` key.

To get these keys one should register at https://docsearch.algolia.com/

@jpradocueva can you take a look and get this Algolia API keys?

**Comment by jpradocueva** [comment]
@rubystream I will send you the email that I have received, the code is:

![image](https://user-images.githubusercontent.com/3258579/140971728-9f2e9dcc-f2b8-4a15-be72-bb4ec281688b.png)

**Comment by jpradocueva** [comment]
@rubystream by reading the information in this link https://docsearch.algolia.com/docs/what-is-docsearch/ I cannot find -why the Algolia search is still not working.

The PR #21 has introduced only a subset of the information provided by the Algolia team. Could that be the reason?

**Comment by rubystream** [comment]
The utilise multi-language approach with en-US as default one. In order to utilise the search capabilities the `language` has to be added in [lwm2m](https://github.com/algolia/docsearch-configs/blob/master/configs/lwm2m.json) config.

It should be added as PR with changes similar to ones in [nuxt router](https://github.com/algolia/docsearch-configs/blob/master/configs/next_router_vuejs.json) one. In particular the parts needed to be added are:

```bash
"selectors" {
  ...
   "language": {
     "selector": "/html/@lang",
     "type": "xpath",
     "global": true,
     "default_value": "en-US"
   }
},
"custom_settings": {
  "attributesForFaceting": [
    "language"
  ]
},
```
